### ISSUE TITLE
Request of a correction (HMC5883L.cpp : ln176)

### ISSUE THREAD

**Issue by EmuAi** [Seeed-Studio/Grove_3Axis_Digital_Compass_HMC5883L#6]
About the function,
`
short HMC5883L::setMeasurementMode(uint8_t mode) {
    write(MODE_REGISTER, mode);
}
`
I believe it needs to be corrected to return some value.

Best.

**Comment by ackPeng** [comment]
@EmuAi Is the value returned incorrect now? Could you please provide more information?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
